require 'execjs/runtime'

module ExecJS
  class RhinoRuntime < Runtime
    class Context < Runtime::Context
      def create_context
        @rhino_context = org.mozilla.javascript.Context.enter
        @rhino_scope = @rhino_context.initStandardObjects
        org.mozilla.javascript.Context.exit
      end

      def evaluate_string(str)
        org.mozilla.javascript.Context.enter(@rhino_context)
        begin
          @rhino_context.evaluateString(@rhino_scope, str, '<eval>', 1, nil)
        ensure
          org.mozilla.javascript.Context.exit
        end
      rescue org.mozilla.javascript.EvaluatorException => e
        if e.message =~ /generated bytecode for method exceeds 64K limit/
          # Rhino can fail for large scripts with optimizations enabled
          @rhino_context.setOptimizationLevel(-1)
          retry
        end
        raise RuntimeError, e.message
      rescue org.mozilla.javascript.JavaScriptException, org.mozilla.javascript.EcmaError => e
        raise ProgramError, e.message
      end
    end

    def name
      'rhino'
    end

    def available?
      require 'rhino/jar_path'
      require Rhino::JAR_PATH
      !org.mozilla.javascript.Context.nil?
    rescue LoadError
      false
    end
  end
end
