require "execjs/runtime"

module ExecJS
  class RubyRhinoRuntime < Runtime
    class Context < Runtime::Context
      def create_context
        @rhino_context = org.mozilla.javascript.Context.enter()
        @rhino_scope = @rhino_context.initStandardObjects();
      end

      def evaluate_string(str)
        @rhino_context.evaluateString(@rhino_scope, str, "<eval>", 1, nil)
      rescue org.mozilla.javascript.EvaluatorException => e
        if e.message =~ /generated bytecode for method exceeds 64K limit/
          # Rhino can fail for large scripts with optimizations enabled
          @rhino_context.setOptimizationLevel(-1);
          retry
        end
        raise RuntimeError, e.message
      rescue org.mozilla.javascript.JavaScriptException, org.mozilla.javascript.EcmaError => e
        raise ProgramError, e.message
      rescue org.mozilla.javascript.EvaluatorException => e
        raise RuntimeError, e.message
      end
    end

    def name
      "therubyrhino (Rhino)"
    end

    def available?
      require "rhino/jar_path"
      load Rhino::JAR_PATH
      true
    rescue LoadError
      false
    end
  end
end
